name: 'Go tests'
canonical: 'stack-golang'
status: 'public'
description: 'This stack will allow you to run golang tests'
image: 'https://raw.githubusercontent.com/cycloid-community-catalog/stack-golang/master/icon.jpg'
keywords:
  - 'golang'
  - 'tests'
  - 'cycloid'
technologies:
  - technology: 'golang'
    version: 'n/a'
author: 'Cycloid'
type: 'stack'
config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/pipeline.yml'
    variables:
          path: 'pipeline/variables.sample.yml'
